{% set name = "openff-amber-ff-ports" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-amber-ff-ports/archive/v{{ version }}.tar.gz
  sha256: a1246559138e47f44a858bb329658247439ed80a32349638f715046f4432e02c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - setuptools

test:
  requires:
    - openff-toolkit
  imports:
    - openff.amber_ff_ports
  files:
    - test_loadable.py
  commands:
    - python test_loadable.py

about:
  home: https://openforcefield.org/
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: Force fields released by the Open Force Field Initiative.
  description: |
    The provided OFFXML (force field) files are successive versions
    of a SMIRNOFF port of ff14SB, an protein force field from the
    Amber community.
  doc_url: https://github.com/openforcefield/openff-amber-ff-ports
  dev_url: https://github.com/openforcefield/openff-amber-ff-ports

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
